
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RANDY
 */
public class LibrosVirtuales extends javax.swing.JFrame {
CargaIndividual Ci = new CargaIndividual();
BiblioVirtual Bv = new BiblioVirtual();

int n;

    /**
     * Creates new form LibrosVirtuales
     */
    public LibrosVirtuales() {
        initComponents();
        setLocationRelativeTo(null);
       
        
        String[][] matriz = new String [Bv.getListaVirtual().length][100];
        
        
       for (int i = 0; i < Bv.getListaVirtual().length; i++) {
           
         
           
         if(Bv.getListaVirtual()[i] != null){
             
              if(Ci.getListaBiblios()[i].getTipo() == "Libro Virtual"){
             
             
                matriz[i][13]= Bv.getListaVirtual()[i].getUsuario();
                matriz[i][0]= Bv.getListaVirtual()[i].getTitulo();
                matriz[i][1]= Bv.getListaVirtual()[i].getAutor();
               matriz[i][2]= Bv.getListaVirtual()[i].getAño();
               matriz[i][3]= Bv.getListaVirtual()[i].getPalabrasClave();
               matriz[i][4]= Bv.getListaVirtual()[i].getDescripcion();
               matriz[i][5]= Bv.getListaVirtual()[i].getTemas();
               matriz[i][6]= Bv.getListaVirtual()[i].getEdicion();
               matriz[i][7]= Bv.getListaVirtual()[i].getArea();
               matriz[i][8]= Bv.getListaVirtual()[i].getCopias();
               matriz[i][9]= Bv.getListaVirtual()[i].getCategoria();
               matriz[i][10]= Bv.getListaVirtual()[i].getDisponibles();
               matriz[i][11]= Bv.getListaVirtual()[i].getISBN();
               matriz[i][12]= Bv.getListaVirtual()[i].getTipo();

              }
               
               
       }
         } 
        
       
        String[] encabezado = {"Libros", "Autor", "Año", "Palabras Clave", "Descripcion", "Temas", "Edicion", "Area", "Copias", "Categoria", "Disponibles", "ISBN", "Tipo"};
        TablaLibros.setModel(new DefaultTableModel(
           matriz,
           encabezado
       ));
        TablaLibros.getColumnModel().getColumn(0).setMaxWidth(100);
        TablaLibros.getColumnModel().getColumn(0).setMinWidth(100);
        TablaLibros.getColumnModel().getColumn(1).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(1).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(2).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(2).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(3).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(3).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(4).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(4).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(5).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(5).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(6).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(6).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(7).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(7).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(8).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(8).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(9).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(9).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(10).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(10).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(11).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(11).setMinWidth(0);
        TablaLibros.getColumnModel().getColumn(12).setMaxWidth(0);
        TablaLibros.getColumnModel().getColumn(12).setMinWidth(0);
         
    }
    
    public void habilitarEliminar(){
    
        if(!Txt_Titulo.getText().isEmpty()){
        EliminarLibrosVirtuales.setEnabled(true);
        
        }else{
            EliminarLibrosVirtuales.setEnabled(false);
        
        }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLibros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt__Usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_Titulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_Autor = new javax.swing.JTextField();
        Txt_Año = new javax.swing.JTextField();
        Txt_Temas = new javax.swing.JTextField();
        Txt_Descripcion = new javax.swing.JTextField();
        Txt_Edicion = new javax.swing.JTextField();
        Txt_Area = new javax.swing.JTextField();
        Txt_Categoria = new javax.swing.JTextField();
        Txt_Isbn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Txt_PalabrasClave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        EliminarLibrosVirtuales = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Txt_Tipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facultad.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/biblioteca.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Biblioteca Virtual");

        TablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libro"
            }
        ));
        TablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaLibros);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoUsuario.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel4.setText("Usuario:");

        Txt__Usuario.setEditable(false);
        Txt__Usuario.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        Txt__Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt__UsuarioActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Portada.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel5.setText("Titulo");

        Txt_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TituloActionPerformed(evt);
            }
        });
        Txt_Titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_TituloKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel7.setText("Autor");

        Txt_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AutorActionPerformed(evt);
            }
        });

        Txt_Año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AñoActionPerformed(evt);
            }
        });

        Txt_Temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TemasActionPerformed(evt);
            }
        });

        Txt_Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DescripcionActionPerformed(evt);
            }
        });

        Txt_Edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EdicionActionPerformed(evt);
            }
        });

        Txt_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AreaActionPerformed(evt);
            }
        });

        Txt_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CategoriaActionPerformed(evt);
            }
        });

        Txt_Isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_IsbnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel10.setText("Año");

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel9.setText("Palabras Clave");

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel11.setText("Descripcion");

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel12.setText("Temas");

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel13.setText("Edicion");

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel14.setText("Area");

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel15.setText("Categoria");

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel16.setText("ISBN");

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel17.setText("Tipo");

        EliminarLibrosVirtuales.setText("Eliminar");
        EliminarLibrosVirtuales.setEnabled(false);
        EliminarLibrosVirtuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarLibrosVirtualesActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Txt_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Libro", "Revista", "Tesis", "Libro Virtual" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel6)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_Año, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(Txt_Edicion)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16)
                                            .addComponent(Txt_Temas, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(Txt_Isbn))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Txt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(78, 78, 78)
                                                    .addComponent(jLabel11))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Txt_PalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EliminarLibrosVirtuales, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_Area, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(Txt_Categoria))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt__Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt__Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_PalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(EliminarLibrosVirtuales, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaLibrosMouseClicked
        // TODO add your handling code here:
        int seleccionar=TablaLibros.rowAtPoint(evt.getPoint());
        Txt_Titulo.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 0)));
        Txt_Autor.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 1)));
        Txt_Año.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 2)));
        Txt_PalabrasClave.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 3)));
        Txt_Descripcion.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 4)));
        Txt_Temas.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 5)));
        Txt_Edicion.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 6)));
        Txt_Area.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 7)));
        
        Txt_Categoria.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 9)));
        
        Txt_Isbn.setText(String.valueOf(TablaLibros.getValueAt(seleccionar, 11)));
        Txt_Tipo.setSelectedItem(String.valueOf(TablaLibros.getValueAt(seleccionar, 12)));
        
        
        
        
        
        
        
   

        
        

    }//GEN-LAST:event_TablaLibrosMouseClicked

    private void Txt__UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt__UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt__UsuarioActionPerformed

    private void Txt_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TituloActionPerformed

    private void Txt_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AutorActionPerformed

    private void Txt_AñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AñoActionPerformed

    private void Txt_TemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TemasActionPerformed

    private void Txt_DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DescripcionActionPerformed

    private void Txt_EdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EdicionActionPerformed

    private void Txt_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AreaActionPerformed

    private void Txt_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CategoriaActionPerformed

    private void Txt_IsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_IsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_IsbnActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        BiblioVirtual newframe = new BiblioVirtual();

        newframe.setVisible(true);
        
        String User = Txt__Usuario.getText(); 
        BiblioVirtual.Txt_Usuario.setText(User);
        

        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void EliminarLibrosVirtualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarLibrosVirtualesActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < Bv.getListaVirtual().length; i++) {
            if(Bv.getListaVirtual()[i] != null){
                if(Bv.getListaVirtual()[i].getTitulo().equals(Txt_Titulo.getText())){
                    Bv.getListaVirtual()[i] = null;

                }

            }

        }
    }//GEN-LAST:event_EliminarLibrosVirtualesActionPerformed

    private void Txt_TituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TituloKeyReleased
        // TODO add your handling code here:
        habilitarEliminar();
    }//GEN-LAST:event_Txt_TituloKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrosVirtuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrosVirtuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrosVirtuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrosVirtuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrosVirtuales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarLibrosVirtuales;
    private javax.swing.JButton Regresar;
    private javax.swing.JTable TablaLibros;
    private javax.swing.JTextField Txt_Area;
    private javax.swing.JTextField Txt_Autor;
    private javax.swing.JTextField Txt_Año;
    private javax.swing.JTextField Txt_Categoria;
    private javax.swing.JTextField Txt_Descripcion;
    private javax.swing.JTextField Txt_Edicion;
    private javax.swing.JTextField Txt_Isbn;
    private javax.swing.JTextField Txt_PalabrasClave;
    private javax.swing.JTextField Txt_Temas;
    private javax.swing.JComboBox<String> Txt_Tipo;
    private javax.swing.JTextField Txt_Titulo;
    public static javax.swing.JTextField Txt__Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
