
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RANDY
 */
public class PantallaUsuarios extends javax.swing.JFrame {
       CrearUsuario Cu = new CrearUsuario();
       BiblioVirtual Bv = new BiblioVirtual();
       CargaIndividual Ci = new CargaIndividual();
       private static DatosReportes[] ListaReportes = new DatosReportes[100];
    /**
     * Creates new form PantallaUsuarios
     */
    public PantallaUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    DatosReportes[] redimensionarArre(DatosReportes[] arreglo){
        DatosReportes[] temporal = new DatosReportes[arreglo.length + 1];
        for (int i = 0; i < arreglo.length; i++) {
            temporal[i] = arreglo[i];
        }
        return temporal;
    }
    
    Boolean hayespacio1(DatosReportes[] arreglo){
        Boolean espacio = false;
        for (int i = 0; i < arreglo.length; i++) {
            if(arreglo[i] == null){
                espacio=true;
                break; 
            }
        }
        return espacio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_Apellido = new javax.swing.JTextField();
        BibliotecaVirtual = new javax.swing.JButton();
        Prestamo = new javax.swing.JButton();
        CerrarSesión = new javax.swing.JButton();
        CargarDatos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(751, 509));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facultad.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/biblioteca.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoUsuario.png"))); // NOI18N

        TxtUsuario.setEditable(false);
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel6.setText("ID");

        Txt_ID.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");

        Txt_Nombre.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel9.setText("Apellido");

        Txt_Apellido.setEditable(false);

        BibliotecaVirtual.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        BibliotecaVirtual.setText("Biblioteca Virtual");
        BibliotecaVirtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BibliotecaVirtualActionPerformed(evt);
            }
        });

        Prestamo.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        Prestamo.setText("Prestamo de Libro");
        Prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestamoActionPerformed(evt);
            }
        });

        CerrarSesión.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        CerrarSesión.setText("Cerrar Sesión");
        CerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesiónActionPerformed(evt);
            }
        });

        CargarDatos.setText("Cargar Datos");
        CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatosActionPerformed(evt);
            }
        });

        jButton1.setText("Existencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(491, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BibliotecaVirtual)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CerrarSesión, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Prestamo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BibliotecaVirtual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CargarDatos))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CerrarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesiónActionPerformed
        // TODO add your handling code here:
        
         if (hayespacio1(getListaReportes())){
            ListaReportes= redimensionarArre(getListaReportes());
        
        for (int i = 0; i <= getListaReportes().length; i++) {
            
            if(getListaReportes()[i] == null){
                if(Bv.getListaVirtual()[i].getTipo() != "Libro Virtual"){
            
            ListaReportes = redimensionarArre(getListaReportes());
             ListaReportes[i] = new DatosReportes(Bv.getListaVirtual()[i].getUsuario(), Bv.getListaVirtual()[i].getAutor(), Bv.getListaVirtual()[i].getTitulo(), Bv.getListaVirtual()[i].getAño(), Bv.getListaVirtual()[i].getPalabrasClave(), Bv.getListaVirtual()[i].getDescripcion(), Bv.getListaVirtual()[i].getTemas(), Bv.getListaVirtual()[i].getEdicion(), Bv.getListaVirtual()[i].getArea(), Bv.getListaVirtual()[i].getCopias(), Bv.getListaVirtual()[i].getCategoria(), Bv.getListaVirtual()[i].getDisponibles(), Bv.getListaVirtual()[i].getISBN(), Bv.getListaVirtual()[i].getTipo());
            
             
             PantallaPrincipal newframe = new PantallaPrincipal();

        newframe.setVisible(true);

        this.dispose();
            }
                else{
                
                PantallaPrincipal newframe = new PantallaPrincipal();

        newframe.setVisible(true);

        this.dispose();
                
                }
            }
            
        }
        
        
        
         }
         
    }//GEN-LAST:event_CerrarSesiónActionPerformed

    private void CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatosActionPerformed
        // TODO add your handling code here:
        
        String[][] matriz = new String[Cu.getListaUsuarios().length][5]; 
            
        for (int i = 0; i < Cu.getListaUsuarios().length; i++) {
            if(Cu.getListaUsuarios()[i] != null) { 
                
                matriz[i][1]=Cu.getListaUsuarios()[i].getID();
                matriz[i][2]= Cu.getListaUsuarios()[i].getNombre();
                matriz[i][3]= Cu.getListaUsuarios()[i].getApellido();
                matriz[i][4]="" + Cu.getListaUsuarios()[i].getUsuario();
                
                
                if(matriz[i][4].equals(TxtUsuario.getText())) {
                    Txt_ID.setText(matriz[i][1]); 
                    Txt_Nombre.setText(matriz[i][2]);
                Txt_Apellido.setText(matriz[i][3]);
                
                
                

                }
            }
            
        }
        
    }//GEN-LAST:event_CargarDatosActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void BibliotecaVirtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BibliotecaVirtualActionPerformed
        // TODO add your handling code here:
        BiblioVirtual newframe = new BiblioVirtual();

        newframe.setVisible(true);
        
        String User = TxtUsuario.getText();
        BiblioVirtual.Txt_Usuario.setText(User);  

        this.dispose();
    }//GEN-LAST:event_BibliotecaVirtualActionPerformed

    private void PrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestamoActionPerformed
        // TODO add your handling code here:
         PrestamoLibros newframe = new PrestamoLibros();

        newframe.setVisible(true);
        
        String User = TxtUsuario.getText();
        PrestamoLibros.Txt_Usuario.setText(User);  

        this.dispose();
    }//GEN-LAST:event_PrestamoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String cadenaExistencias = "<!Doctype html>\n" +
"<html>\n" +
"<head>\n" +
" <title Reporte de Existencias>\n" +
"</title>\n" +
"</head>\n" +
"<style> table, th, td {\n" +
"		border:1px solid rgb(156, 148, 148);\n" +
"		}\n" +
"</style>\n" +
"<body>\n" +
"\n" +
"<h1 style=\"color:black; text-align:center;\">Reporte de Existencias</h1>\n" +
"<h2 style=\"color:black; text-align:center;\">Libros Disponibles Para el Usuario</h2>\n" +
"<br>\n" +              
"<table style=\"margin: 0 auto;\">" +
    "<tr>"+
	"<th>Titulo</th>\n"+
	"<th>Autor</th>\n"+
        "<th>Año</th>\n"+
        "<th>Edicion</th>\n"+         
	"<th>Tipo</th>\n"+ 
	
"</tr>"  ;
        
        for (int i = 0; i < Ci.getListaBiblios().length ; i++) {
            if(Ci.getListaBiblios()[i] != null){
            
            cadenaExistencias += "<tr>";
            cadenaExistencias += "<td>" + Ci.getListaBiblios()[i].getTitulo() + "</td>";
            cadenaExistencias += "<td>" + Ci.getListaBiblios()[i].getAutor()+ "</td>";
            cadenaExistencias += "<td>" + Ci.getListaBiblios()[i].getAño()+ "</td>";
            cadenaExistencias += "<td>" + Ci.getListaBiblios()[i].getEdicion()+ "</td>";
            cadenaExistencias += "<td>" + Ci.getListaBiblios()[i].getTipo()+ "</td>";
            
            cadenaExistencias += "</tr>";
            }
            
        }
    
    cadenaExistencias += "</table>\n" +
            
        "<body>\n" +
        "\n" +
        "</html>"  ; 
        
       
        
        File Existencias = new File("reporteExistencias.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(Existencias));
            bw.write(cadenaExistencias);
            bw.close();
            
        } catch (Exception e) {
        }
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BibliotecaVirtual;
    private javax.swing.JButton CargarDatos;
    private javax.swing.JButton CerrarSesión;
    private javax.swing.JButton Prestamo;
    public static javax.swing.JTextField TxtUsuario;
    private javax.swing.JTextField Txt_Apellido;
    private javax.swing.JTextField Txt_ID;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ListaReportes
     */
    public static DatosReportes[] getListaReportes() {
        return ListaReportes;
    }
}
